CompileFlags:
  Add:
    [
      -std=c++20,
      -stdlib=libc++,
      -pedantic-errors,
      -Wall,
      -Weffc++,
      -Wextra,
      -Wconversion,
      -Werror,
    ]

Diagnostics:
  ClangTidy:
    Add:
      [
        bugprone-*,
        clang-analyzer-*,
        modernize-*,
        performance-*,
        portability-*,
        readability-*,
      ]
